### ISSUE TITLE
Missing 3D models?

### ISSUE THREAD

**Issue by jdarpinian** [sqfmi/watchy-hardware#1]
I'm new to kicad, so forgive me if I'm missing something, but it seems like the project references at least one 3D model that's not included in the repo here, ${KIPRJMOD}/3D/PagerMotor.STEP. Also the latest kicad libraries (https://github.com/kicad/kicad-packages3d) do not include ${KISYS3DMOD}/Button_Switch_SMD.3dshapes/SKSCLB.STEP or Capacitors_SMD.3dshapes/C_0603.wrl among others. Do I need to install extra libraries, or use a different version of kicad (currently 5.1.9)?

**Comment by sqfmi** [comment]
Updated project to reference correct models, should work with current version of KiCad

**Comment by jdarpinian** [comment]
Awesome! Thanks!
