### ISSUE TITLE
Colour and greyscale e-ink compatibility

### ISSUE THREAD

**Issue by benevpi** [sqfmi/watchy-hardware#12]
There are other e-ink screens in the same form-factor and (what looks like -- I'm still trying to verify) the same connector including a grey scale (rather than just black and white): https://www.good-display.com/product/205.html

and a black / white / red 3 colour option from waveshare (I'm less sure about this pinout and still trying to find a datasheet): https://www.waveshare.com/1.54inch-e-Paper-B.htm

Looks like they're compatible with the same libraries used. Does anyone know if these should work with the hardware? Has anyone tried them out?

**Comment by DarkZeros** [comment]
I can confirm they work, just plug them and change the source code.
Just... remember that a color display takes 20seconds to update. Can only do a full update. And will therefore use like 3x battery.
