### ISSUE TITLE
New PCB revision released with no documentation

### ISSUE THREAD

**Issue by miekush** [sqfmi/watchy-hardware#13]
Recently I purchased a [Watchy from Mouser](https://www.mouser.com/ProductDetail/SQFMI/SQFMI-WATCHY-10?qs=DRkmTr78QARN9VSJRzqRxw%3D%3D) and I noticed some issues with time not updating using the example watch faces. After some debugging I noticed the PCB shown in the documentation and hardware design files differed from my board. It appears a new version has been released which has replaced the previous DS3231 RTC with a [PCF8563](https://www.nxp.com/docs/en/data-sheet/PCF8563.pdf). Unfortunately it seems this repo, the SW library and all of the user documentation has not been updated.

![New Watchy PCB](https://i.imgur.com/97LWjkh.jpg)

**Comment by filipproch** [comment]
@miekush not sure if you are on Discord, so sharing here as well
![image](https://user-images.githubusercontent.com/1387116/144134807-351adace-f159-4def-859a-0d12e05a5b0a.png)

**Comment by sqfmi** [comment]
Sorry for the delay, pushed to v1.5

**Comment by miekush** [comment]
No worries! Thank you.
