### ISSUE TITLE
STEP models won't open in Solidworks 2020

### ISSUE THREAD

**Issue by Snowflake6** [sqfmi/watchy-hardware#2]
![image](https://user-images.githubusercontent.com/5349216/104389195-bd9c8300-54ef-11eb-9d77-dcc6b7058c7a.png)

Same result with Watchy.step and Watchy_battery.step

**Comment by sqfmi** [comment]
We tried opening the files just now and it appears ok:

![Watchy_Battery step](https://user-images.githubusercontent.com/28943617/104398596-0cacdd00-551d-11eb-9ecd-697df742dff6.png)

We Googled the error you saw and found the following solutions:

https://www.cati.com/blog/2019/03/bypassing-warning-encountered-invalid-record-index-during-step-import/
https://www.javelin-tech.com/blog/2018/11/encountered-invalid-record-index-solidworks/

Let us know if these solve the problem for you, we are not familiar with Solidworks so we were unable to reproduce the error

**Comment by Snowflake6** [comment]
Well, that was truly strange.  I loaded it on my home computer, same Solidworks license, and it opened up.  I'll try again when I get to the office tomorrow but it appears to work, it's got to be something with my SW install at the office.  Thanks!  I think this can be closed for now.
![image](https://user-images.githubusercontent.com/5349216/104406348-f5b5bd00-5513-11eb-96ed-ff8192d90126.png)

**Comment by Faroukt14** [comment]
Hello where i can find the step files of the watch
